export const QUERY_KEY = {
  MONTH_SAVE: 'month-save',
  MONTH_VIEW: 'month-view',
  MOST_VIEW: 'most-view',
  WEEK_CHART: 'week-chart',
  MONTH_CHART: 'month-chart',
  MONTH_STATS: 'month-stats',
  CLICK_TOTAL_CHART: 'click-total-chart',
  CARD_SELECT_LIST: 'card-select-list',
  CARD_INTERACTION: 'card-interaction',
  USER_IP: 'user-ip',
  CARD_SOCIAL_LIST: 'card-social-list',
  CARD_SLUG: 'card-slug',
  CARD_NICK_NAME: 'card-nick-name',
  CARD_TITLE: 'card-title',
  TEMPLATES: 'templates',
};
